### ISSUE TITLE
PHP Fatal error when a variable is missing from operation name and dictionary of values

### ISSUE THREAD

**Issue by leoloso** [youshido-php/GraphQL#238]
I get the following exception:

```
PHP Fatal error:  Uncaught Error: Call to a member function hasDefaultValue() on null in .../vendor/youshido/graphql/src/Execution/Request.php:69
```

When executing a query which includes a variable, but:

1. The variable was not defined in the operation name, AND
2. The variable value was not passed in the dictionary

<a href="https://newapi.getpop.org/graphiql/?query=%23 This doesn't work%0Aquery GetPosts {%0A%20 posts {%0A%20%20%20 id%0A%20%20%20 title%0A%20%20%20 date(format%3A%24date)%0A%20 }%0A}&operationName=GetPosts">Click on this link</a> and run the query to reproduce the error (it doesn't show the PHP exception error though, only that there was an internal server error)

**Comment by Jalle19** [comment]
Can you provide the full stacktrace?

**Comment by leoloso** [comment]
```
[12-Jan-2020 10:00:26 UTC] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /Users/leo/Sites/PoPAPIWP/vendor/youshido/graphql/src/Execution/Request.php on line 66
[12-Jan-2020 10:00:26 UTC] PHP Fatal error:  Uncaught Error: Call to a member function hasDefaultValue() on null in /Users/leo/Sites/PoPAPIWP/vendor/youshido/graphql/src/Execution/Request.php:69
Stack trace:
#0 /Users/leo/GitRepos/GitHub/Libraries/getpop/api-graphql-query/src/Schema/GraphQLQueryConvertor.php(255): Youshido\GraphQL\Execution\Request->__construct(Array, NULL)
#1 /Users/leo/GitRepos/GitHub/Libraries/getpop/api-graphql-query/src/Schema/GraphQLQueryConvertor.php(40): PoP\GraphQLAPIQuery\Schema\GraphQLQueryConvertor->parseAndCreateRequest('# query {\n#   _...', NULL)
#2 /Users/leo/GitRepos/GitHub/Libraries/getpop/api-graphql-request/src/Hooks/VarsHooks.php(60): PoP\GraphQLAPIQuery\Schema\GraphQLQueryConvertor->convertFromGraphQLToFieldQuery('# query {\n#   _...', NULL)
#3 /Users/leo/GitRepos/GitHub/Libraries/getpop/api-graphql-request/src/Hooks/VarsHooks.php(30): PoP\GraphQLAPIRequest\Hooks\VarsHooks->processURLParamVars(Array)
#4 /Users/leo/Sites/PoPAPIWP/wp/wp-includes/class-wp-hook.php(288): PoP\GraphQLAPIRequest\Hooks\VarsHooks->addURLPar in /Users/leo/Sites/PoPAPIWP/vendor/youshido/graphql/src/Execution/Request.php on line 69
```

My code, from which the error happens, is this line:

```php
$request = new Request($parsedData, $variables);
```

from this code in my library (not Youshido):

```php
protected function parseAndCreateRequest($payload, $variables = []): Request
{
    if (empty($payload)) {
        throw new InvalidArgumentException($this->translationAPI->__('Must provide an operation.'));
    }

    $parser  = new Parser();
    $parsedData = $parser->parse($payload);
    $request = new Request($parsedData, $variables);

    // If the validation fails, it will throw an exception
    (new RequestValidator())->validate($request);

    // Return the request
    return $request;
}
```

**Comment by Jalle19** [comment]
Try setting the default value of `$variables` to `null` instead of `[]`.

**Comment by leoloso** [comment]
I just did, it still fails, same exception

**Comment by leoloso** [comment]
Please notice that if you pass a variables dictionary including the variable `date` it doesn't throw an exception. It only does when variable `date` is not present in the dictionary (and not defined in the operation name)

**Comment by Jalle19** [comment]
I have to try reproducing on my own, it should fail with a better error, like "Variable $date not submitted".

**Comment by leoloso** [comment]
Currently it fails with a better error when either the variable is defined in the operation name but not in the variables, or the other way around. Only when both are missing it throws an exception. 

I believe it should be straightforward to reproduce, since there's nothing special in my code.

**Comment by Jalle19** [comment]
I fixed it in #239. It will still error out of course, but the exception will come from the request validator instead of the parser.

**Comment by leoloso** [comment]
This problem can be fixed by checking in `Execution/Request.php`, function `__construct`, that the variable that produces the exception is not `null`.

Currently:

```php
$variable = $ref->getVariable();
if ($variable->hasDefaultValue()) {
```

Fix:

```php
$variable = $ref->getVariable();
if (!is_null($variable) && $variable->hasDefaultValue()) {
```

If it is `null`, then the ensuing error message `"Variable %s hasn't been submitted"` is good enough (at least for the time being). Would you agree? Should I submit a PR? (I need to fix it, since this problem is happening in my PROD)

**Comment by leoloso** [comment]
Ops, I closed by mistake. 

This branch in my fork handles this solution a bit better:

https://github.com/getpop/graphql-parser/tree/fix-exception-when-no-args-declared

**Comment by Jalle19** [comment]
Feel free to make a PR. I don't remember what the issue was with my previous attempt anymore, I got a feeling it's not as easy to fix as it sounds like. Maybe your solution works better though.

**Comment by leoloso** [comment]
My solution is simple, because it notices that, if the variable was not defined in the operation, then this line will return `null`:

```php
$variable = $ref->getVariable();
```

Maybe this could be handled more elegantly, but this solution, at least, avoids the `RuntimeException` that was breaking my server.

I'm submitting the PR now
